[package]
name = "regex_dfa"
version = "0.1.0"
authors = ["Joe Neeman <joeneeman@gmail.com>"]
description = "A crate for turning regexes into DFAs."
documentation = "http://jneem.github.io/regex-dfa"
homepage = "http://jneem.github.io/regex-dfa"
repository = "http://github.com/jneem/regex-dfa"
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
regex = "*"
regex-syntax = "*"
bit-set = "*"

[dev-dependencies]
rand = "0.3"

[[bench]]
name = "dynamic"
path = "benches/bench_dynamic.rs"
test = false
bench = true

[[bench]]
name = "dfa"
path = "benches/bench_dfa.rs"
test = false
bench = true

